name: xBrew
options:
  bundleIdPrefix: asia.xdev
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  # App Store settings
  APP_CATEGORY: public.app-category.utilities
  APP_PRICE_TIER: "0" # FREE

targets:
  xBrew:
    type: application
    platform: macOS
    sources:
      - path: xBrew
        excludes:
          - "**/*.md"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: asia.xdev.xBrew
      PRODUCT_NAME: xBrew
      INFOPLIST_FILE: xBrew/Resources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_ENTITLEMENTS: xBrew/Resources/xBrew.entitlements
      COMBINE_HIDPI_IMAGES: YES
      DEVELOPMENT_TEAM: ""
      ENABLE_HARDENED_RUNTIME: YES
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: NO
      LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_VERSION: "5.0"
